/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SoCool.view.Login', {
    extend: 'Ext.Container',
    id: 'viewLogin',
    config: {
        padding: 20,
        layout:{
	    	type: 'card',
	    	animation: {
		    	type: 'fade'
	    	}
    	},
        items: [
            {
                xtype: 'toolbar',
                title: 'Welcome to SoCool',
                docked: 'top',
                items: [
                   	{
                        xtype: 'button',
                        align: 'left',
                        id: 'goBackFromLogin',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                   	{
                   		flex: 1,
                        xtype: 'button',
                        id: 'fbLoginBtn',
                        text: 'Login with Facebook'
                    }
                ]
            }    
        ]
    },



    showLoginText: function() {
        this.setHtml([
    	    '<h2>Welcome to SoCool</h2>',
	        '<p>With this app you can arrange your meeting and share your progress with your friends</p>',
	        '<p>In order to use SoCool with Friends you must sign in with your Facebook account.</p>',
        ].join(''));
    }

});