/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SoCool.view.Map', {
    extend: 'Ext.Container',
    id: 'viewMap',
//    xtype: 'login',
    config: {
        padding: 20,
        layout:{
	    	type: 'card',
	    	animation: {
		    	type: 'fade'
	    	}
    	},
        items: [
            {
                xtype: 'toolbar',
                title: 'Map Page',
                docked: 'top',
                items: [
                   	{
                        xtype: 'button',
                        align: 'left',
                        id: 'goBackFromViewMap',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
        ]
    },



    showMapText: function() {

        this.setHtml([
        '<h2>Welcome to the Map page in SoCool</h2>',
        '<p>This page is supposed to show the meeting spots and bookings in actual Map</p>',
        '<p>Soon will be filled. Wait plz.</p>',
        ].join(''));
    }

});