/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SoCool.view.Post', {

    extend: 'Ext.Panel',
    id: 'viewPost',
    config: {
        padding: 20,
        scrollable: true,
        layout:{
	    	type: 'card',
	    	animation: {
		    	type: 'fade'
	    	}
    	},
        items: [
            {
                xtype: 'toolbar',
                title: 'New Meeting ',
                docked: 'top',
                items: [
                   	{
                        xtype: 'button',
                        align: 'left',
                        id: 'backFromPostBtn',
                        ui: 'back',
                        text: 'Back'
                    },
                   	{
                        xtype: 'button',
                        align: 'right',
                        id: 'doPostBtn',
                        text: 'Post'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'titleField',
                        placeHolder: 'Title?'
                    },
                    {
                        xtype: 'textfield',
                        id: 'subtitleField',
                        placeHolder: 'subtitle?'
                    },
                    {
                        xtype: 'textfield',
                        id: 'scheduleField',
                        placeHolder: 'subtitle?'
                    },
                    {
                        xtype: 'textfield',
                        id: 'subtitleField',
                        placeHolder: 'subtitle?'
                    }                    
                ]
            },
            {
                xtype: 'button',
                id: 'addRunButton',
                ui: 'facebook',
                text: 'Add Jog'
            }  
        ]
    }
});