/*
 * File: app/view/Login.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SoCool.view.Post', {

    extend: 'Ext.Panel',
    id: 'viewPost',
    requires: [
        'Ext.field.DatePicker',
        'Ext.form.FieldSet',
        'Ext.field.Number'
    ],
    
    config: {
        padding: 20,
        scrollable: true,
        layout:{
	    	type: 'card',
	    	animation: {
		    	type: 'fade'
	    	}
    	},
        items: [
            {
                xtype: 'toolbar',
                title: 'New Meeting ',
                docked: 'top',
                items: [
                   	{
                        xtype: 'button',
                        align: 'left',
                        id: 'backFromPostBtn',
                        ui: 'back',
                        text: 'Back'
                    },
                    {	xtype: 'spacer'},
                   	{
                        xtype: 'button',
                        align: 'right',
                        id: 'doPostBtn',
                        text: 'Post'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'titleField',
                        label: 'Title',
                        placeHolder: 'Title?'
                    },
                    {
                        xtype: 'numberfield',
                        id: 'maxMembField',
                        label: 'Members',
                        placeHolder: 'How many members?'
                    },
                    {
                        xtype: 'textfield',
                        id: 'locationField',
                        label: 'Location',
                        placeHolder: 'Where?'
                    },

                    
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'datepickerfield',
                                label: 'MeetingDate',
                                id: 'meetingDate',
                                name: 'meetingDate',
                                value: new Date()
                                
                            },
                            {
                                xtype: 'numberfield',
                                id: 'hourField',
                                label: 'Hour',
                                placeHolder: 'What time?'
                            },
                            {
                                xtype: 'numberfield',
                                id: 'minField',
                                label: 'Minute',
                                placeHolder: 'What time?'
                            }   
                        ]
                        
                    
                    },

                    {
                        xtype: 'textareafield',
                        id: 'descriptionField',
                        label: 'Description',
                        placeHolder: 'Appeal yourself'
                    }                 
                ]
            },
        ]
    }
});